version: "3.9"
services:
  # Server
  app:
    build: ./app
    # ports:
    #   - "3000:3000"
    # expose:
    #   - 3000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 6