# Deployment Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: hanm13
  labels:
    group: discord-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      tier: backend
  #POD
  template:
    metadata:
      labels:
        app: app
        tier: backend
    spec:
      containers:
        - name: node
          image: hanm13/verify-bot:latest
          env:
            # Define the environment variable
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: configmap-token-1
                  # Specify the key associated with the value
                  key: TOKEN